"use strict";
exports.__esModule = true;
var BuilderPC_1 = require("./BuilderPC");
var GPU_1 = require("./Component/GPU");
var Ram_1 = require("./Component/Ram");
var Main_1 = require("./Component/Main");
var Chip_1 = require("./Component/Chip");
var Adapter_1 = require("./Component/Adapter");
var builder = new BuilderPC_1.BuilderPC();
var gpu = new GPU_1.GPU();
var ram = new Ram_1.Ram();
var main = new Main_1.Main();
var chip = new Chip_1.Chip();
var adapter = new Adapter_1.Adapter();
builder.buildAdapter(adapter.build(50, 'NVIDIA', 10));
builder.buildChip(chip.build('i9', Chip_1.ChipSocket.AMD462, 'NVIDIA', 220));
builder.buildGPU(gpu.build('RTX2080', GPU_1.GPUMonitor._60HZ, 'NVIDIA', 100));
builder.AddRAM(ram.build(128, Ram_1.RamBus._2226, 'NVIDIA', 24)).AddRAM(ram.build(256, Ram_1.RamBus._2400, 'NVIDIA', 35));
builder.buildMain(main.build('b360', [Chip_1.ChipSocket.ALL], [Ram_1.RamBus._2226, Ram_1.RamBus._2400], [GPU_1.GPUMonitor.ALL], 'NVIDIA', 300));
builder.detailPC();
